### ISSUE TITLE
About the GDFN module

### ISSUE THREAD

**Issue by RexEmperor** [sijang/SpachTransformer#1]
Dear @sijang ,
Firstly, I would like to thank you for your paper's contribution to the advancement of scientific research and for inspiring me.
Secondly, after reading the code section, I have some doubts, I didn't find the GCFN module in the thesis, is it not provided in the thesis or is it written in a more obscure way?

**Comment by sijang** [comment]
Thank you for reaching out! 
You are absolutely right, and I apologize for missing the GCFN earlier. 
Thanks to your input, I've now updated the code to include GCFN. I appreciate your help!

**Comment by RexEmperor** [comment]
Dear @sijang 
I saw that part, thanks so much for the timely update!
